# Crop Yield Dataset - Data Preprocessing

In [52]:
import pandas as pd
import numpy as np

In [53]:
df = pd.read_csv('crop_yield1.csv')
df.head()

,N,P,K,Soil_pH,Soil_Moisture,Soil_Type,Organic_Carbon,Temperature,Humidity,Rainfall,Sunlight_Hours,Wind_Speed,Region,Altitude,Season,Crop_Type,Irrigation_Type,Fertilizer_Used,Pesticide_Used,Crop_Yield_ton_per_hectare
0,179.0,26.0,79.0,7.14,23.02,Loamy,0.31,27.08,60.96,1623.03,8.73,10.52,North,1980.0,Rabi,Sugarcane,Canal,319.77,16.88,77.45
1,128.0,97.0,58.0,4.81,46.13,Clay,0.94,36.02,38.75,1315.22,9.92,13.54,NaN,1868.0,Zaid,Cotton,Drip,154.52,16.75,NaN
2,87.0,74.0,46.0,5.66,61.15,Loamy,1.25,34.65,35.81,1212.18,6.77,4.55,North,14.0,Rabi,Wheat,Canal,146.77,12.64,10.09
3,NaN,97.0,28.0,6.13,62.13,Sandy,0.49,NaN,79.35,NaN,8.29,6.52,North,1623.0,NaN,Rice,Drip,269.40,10.45,10.43
4,80.0,86.0,136.0,4.95,28.65,Sandy,1.51,18.99,44.00,NaN,6.13,NaN,NaN,1019.0,Rabi,Rice,Rainfed,NaN,22.51,9.44

In [54]:
df.shape

(11500, 20)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   N                           10346 non-null  float64
 1   P                           10348 non-null  float64
 2   K                           10330 non-null  float64
 3   Soil_pH                     10349 non-null  float64
 4   Soil_Moisture               10348 non-null  float64
 5   Soil_Type                   10354 non-null  object
 6   Organic_Carbon              10356 non-null  float64
 7   Temperature                 10341 non-null  float64
 8   Humidity                    10324 non-null  float64
 9   Rainfall                    10355 non-null  float64
 10  Sunlight_Hours              10337 non-null  float64
 11  Wind_Speed                  10337 non-null  float64
 12  Region                      10361 non-null  object
 13  Altitude                    10356 non-null  float64
 14  Season                      10340 non-null  object
 15  Crop_Type                   10355 non-null  object
 16  Irrigation_Type             10349 non-null  object
 17  Fertilizer_Used             10354 non-null  float64
 18  Pesticide_Used              10357 non-null  float64
 19  Crop_Yield_ton_per_hectare  10340 non-null  float64
dtypes: float64(15), object(5)
memory usage: 1.8+ MB

In [56]:
df.describe()

,N,P,K,Soil_pH,Soil_Moisture,Organic_Carbon,Temperature,Humidity,Rainfall,Sunlight_Hours,Wind_Speed,Altitude,Fertilizer_Used,Pesticide_Used,Crop_Yield_ton_per_hectare
count,10346.000000,10348.000000,10330.000000,10349.000000,10348.000000,10356.000000,10341.000000,10324.000000,10355.000000,10337.000000,10337.000000,10356.000000,10354.000000,10357.000000,10340.000000
mean,105.197951,56.821995,85.126331,6.502263,40.189771,0.955861,25.090486,59.860401,1548.252134,7.494545,9.485770,1104.202105,205.913578,12.487436,22.481208
std,43.175464,24.520503,37.523708,0.978328,14.453521,0.373530,8.751950,17.430759,719.169827,2.006254,4.890558,638.079511,83.460707,7.226317,24.094336
min,30.000000,15.000000,20.000000,4.800000,15.000000,0.300000,10.000000,30.010000,300.700000,4.000000,1.000000,0.000000,60.000000,0.000000,1.760000
25%,68.000000,35.000000,52.000000,5.660000,27.820000,0.630000,17.480000,44.807500,928.510000,5.740000,5.250000,549.000000,133.170000,6.240000,8.290000
50%,105.000000,57.000000,85.000000,6.520000,40.245000,0.960000,24.950000,59.485000,1552.190000,7.510000,9.480000,1107.000000,205.695000,12.410000,10.275000
75%,142.000000,78.000000,118.000000,7.350000,52.802500,1.280000,32.860000,75.140000,2168.700000,9.200000,13.680000,1659.000000,277.392500,18.730000,24.810000
max,179.000000,99.000000,149.000000,8.200000,64.990000,1.600000,40.000000,89.990000,2799.260000,11.000000,18.000000,2199.000000,349.960000,25.000000,80.990000

In [57]:
df.isnull().sum()

N                             1154
P                             1152
K                             1170
Soil_pH                       1151
Soil_Moisture                 1152
Soil_Type                     1146
Organic_Carbon                1144
Temperature                   1159
Humidity                      1176
Rainfall                      1145
Sunlight_Hours                1163
Wind_Speed                    1163
Region                        1139
Altitude                      1144
Season                        1160
Crop_Type                     1145
Irrigation_Type               1151
Fertilizer_Used               1146
Pesticide_Used                1143
Crop_Yield_ton_per_hectare    1160
dtype: int64

In [58]:
print(df.duplicated().sum())
df.drop_duplicates(inplace=True)

1500

In [59]:
num_cols = df.select_dtypes(include=np.number).columns
cat_cols = df.select_dtypes(exclude=np.number).columns

In [60]:
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

In [61]:
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [62]:
for col in cat_cols:
    df[col] = df[col].str.strip()

In [63]:
for col in cat_cols:
    df[col] = df[col].str.lower()

In [64]:
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    df = df[(df[col] >= lower) & (df[col] <= upper)]

In [65]:
columns_to_check = ['Soil_Type', 'Region', 'Season', 'Crop_Type', 'Irrigation_Type']

for col in columns_to_check:
    print(f"Unique values in '{col}':\n", df[col].value_counts(), "\n")

Unique values in 'Soil_Type':
 Soil_Type
loamy    2780
sandy    1960
silt     1918
clay     1869
Name: count, dtype: int64

Unique values in 'Region':
 Region
south      2430
north      1578
central    1515
east       1504
west       1500
Name: count, dtype: int64

Unique values in 'Season':
 Season
kharif    3433
rabi      2563
zaid      2531
Name: count, dtype: int64

Unique values in 'Crop_Type':
 Crop_Type
rice         2390
wheat        1520
maize        1505
potato       1489
cotton       1480
sugarcane     143
Name: count, dtype: int64

Unique values in 'Irrigation_Type':
 Irrigation_Type
drip         2798
rainfed      1948
canal        1926
sprinkler    1855
Name: count, dtype: int64

In [66]:
from sklearn.preprocessing import LabelEncoder

# Apply Label Encoding for the columns with repeated values
le = LabelEncoder()
for col in columns_to_check:
    df[col] = le.fit_transform(df[col])

df.head()

,N,P,K,Soil_pH,Soil_Moisture,Soil_Type,Organic_Carbon,Temperature,Humidity,Rainfall,Sunlight_Hours,Wind_Speed,Region,Altitude,Season,Crop_Type,Irrigation_Type,Fertilizer_Used,Pesticide_Used,Crop_Yield_ton_per_hectare
1,128.000000,97.00,58.0,4.81,46.13,0,0.94,36.020000,38.75,1315.220000,9.92,13.540000,3,1868.0,2,0,1,154.520000,16.75,22.363264
2,87.000000,74.00,46.0,5.66,61.15,1,1.25,34.650000,35.81,1212.180000,6.77,4.550000,2,14.0,1,5,0,146.770000,12.64,10.090000
3,104.940778,97.00,28.0,6.13,62.13,2,0.49,25.116503,79.35,1547.120192,8.29,6.520000,2,1623.0,0,3,1,269.400000,10.45,10.430000
4,80.000000,86.00,136.0,4.95,28.65,2,1.51,18.990000,44.00,1547.120192,6.13,9.492654,3,1019.0,1,3,2,206.396118,22.51,9.440000
5,104.940778,56.85,73.0,7.23,59.62,2,0.86,22.060000,35.18,2193.220000,10.20,4.220000,2,1488.0,2,1,3,341.130000,23.33,12.880000

In [67]:
for col in columns_to_check:
    print(f"\n{col} Mapping:")
    print(dict(zip(le.classes_, range(len(le.classes_)))))

Soil_Type Mapping:
{'canal': 0, 'drip': 1, 'rainfed': 2, 'sprinkler': 3}

Region Mapping:
{'canal': 0, 'drip': 1, 'rainfed': 2, 'sprinkler': 3}

Season Mapping:
{'canal': 0, 'drip': 1, 'rainfed': 2, 'sprinkler': 3}

Crop_Type Mapping:
{'canal': 0, 'drip': 1, 'rainfed': 2, 'sprinkler': 3}

Irrigation_Type Mapping:
{'canal': 0, 'drip': 1, 'rainfed': 2, 'sprinkler': 3}

In [68]:
df.to_csv("crop_yield_cleaned.csv", index=False)